### ISSUE TITLE
Wrong bullet direction when space ship rotated.

### ISSUE THREAD

**Issue by xquangdang** [xquangdang/SpaceshipHtml5#3]
# Issue
The bullet is shot wrong direction when rotate the ship
# Reproduce step
* Join the game
* Rotate the ship
* Change gun direction by moving mouse
* Hold W to shoot
![screenshot 126](https://cloud.githubusercontent.com/assets/11795757/21428141/1fa2c898-c88b-11e6-8051-4aa4fb5599cb.png)

**Comment by mpnguyen** [comment]
Ok, I will fix

**Comment by mpnguyen** [comment]
Fixed!
